alert:
    telegramnotify: "https://api.telegram.org/bot6968591568:AAGB1jKKJ5ZW22Y7tLvkatG2erC8M0PfOW4/sendMessage?chat_id=-1002019720165&text="
    alertgamethreshold: 100000
    # alertgamethreshold: 6
    alertsinglewinthreshold: 20000
    # alertsinglewinthreshold: 5
isDev: true
currency:
  - key: "THB"
    symbol: "฿"
    multi: 1
  - key: "THB1"
    symbol: "฿"
    multi: 1
 
