mongo: mongodb://myAdmin:myAdminPassword1@47.237.3.219:27017/?authSource=admin
#mongo: mongodb://myUser:123456@192.168.1.2:27017/?authSource=admin
#mongo: mongodb://myAdmin:myAdminPassword1@47.243.173.51:27017/?authSource=admin
DEV: true
BaoZang: 127.0.0.1:11007
Hilo: 127.0.0.1:11009
JinNiu: 127.0.0.1:11013
NiuBi: 127.0.0.1:11005
Roma: 127.0.0.1:11010
RomaX: 127.0.0.1:11011
TuZi: 127.0.0.1:11014
XingYunXiang: 127.0.0.1:11012
YingCaiShen.http.test: :30002
ZhaoCaiMao: 127.0.0.1:11008
admin.http: :11100
gamecenter: 192.168.1.2:11001
gamecenter.http: 192.168.1.2:11004
gateway.http: :11080
proxy: 127.0.0.1:11003
proxy.mq: 192.168.1.2:11002
slots: 127.0.0.1:11006
stats: 127.0.0.1:11015
MaJiang.http.test: :30005
MaJiang2.http.test: :30006
Bonaza.http.test: 127.0.0.1:30007
Olympus.http.test: 127.0.0.1:40001
SugarRush.http.test: :40002


pggateway.http: :50001
pggateway.http.proxy: :50002
pggateway.http.api: :50003
pg_65.http.test: :50004
