## the default empty is OK
# apiurlbase: "https://api.xoioplay.com"

bobetdetailstempurl: "https://public-pg.xoioplay.com/history/1489936.html?sid=1&psid=660cb855859579949c5a0402&api=%2F%2Fapi.xoioplay.com%2Fback-office-proxy%2FReport%2FGetBetHistory&lang=en&gid=1489936"


reverseproxy: 
  "static-pg.xoioplay.com": "https://static.pg-demo.com"
  "m-pg.xoioplay.com": "https://m.pgsoft-games.com"
  "public-pg.xoioplay.com": "https://public.pgsoft-games.com"
