RewardPercent: 25 #个人奖池累计配置千分比
NoAwardPercent: 40 #不中奖千分比
HitBigAwardPercent:
  - 100 #入场爆奖池概率千分比
  - 200
  - 200
  - 200
  - 200
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 200
  - 200
  - 200
  - 200