RewardPercent: 40 #个人奖池累计配置千分比
NoAwardPercent: 200 #不中奖千分比
HitBigAwardPercent:
  - 1000 #入场爆奖池概率千分比
  - 600
  - 500
  - 500
  - 600
  - 500
  - 500
  - 600
  - 500
  - 500
  - 600
  - 500
  - 500
  - 600
  - 500
  - 500
  - 600
  - 500
  - 500
  - 500

