RewardPercent: 30 # 下注的3% 个人奖池累计配置千分比 所有slots 通用,  普通, 购买不算
RewardPercentLess100: 100 #千分比，转动次数小于100次, 当前slots 新手前100次 10% 进奖池, 普通, 购买不算
NoAwardPercent: 200 #个人奖池为负数，不中奖概率千分比  20%不中奖,  优先级最高
Boyibo_times: 0.85 #倍率成功率0.85
Boyibo_count: 0.8 #次数成功率
HitBigAwardPercent: # 进入时刷新
  - 100 #入场爆奖池概率千分比
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
BuyGameBigAwardPercent:
  - 100 #购买完小游戏以后爆奖池千分比
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100